### Listar aprendices
GET http://localhost:8001/aprendices

### Crear aprendiz
POST http://localhost:8001/aprendices
Content-Type: application/json

{
    "nombre": "Laur1a",
    "apellido": "Gómez",
    "email": "laura@example.com",
    "telefono": "3111111111"
}

###
POST http://localhost:8001/aprendices


### Listar programas
GET http://localhost:8001/programas

### Crear programa
POST http://localhost:8001/programas
Content-Type: application/json

{
    "nombre_programa": "Tecnólogo en Análisis y Desarrollo de Software"
}

###
POST http://localhost:8001/programas


### Listar profesiones
GET http://localhost:8001/profesiones

### Crear profesión
POST http://localhost:8001/profesiones
Content-Type: application/json

{
    "nombre_profesion": "Desarrollador Backend"
}


###
POST http://localhost:8001/profesiones