### Listar aprendices
GET http://localhost:8001/aprendices

### Crear aprendiz
POST http://localhost:8001/aprendices
Content-Type: application/json

{
    "nombre": "Laur1a",
    "apellido": "Gómez",
    "email": "laura@example.com",
    "telefono": "3111111111"
}

###
POST http://localhost:8001/aprendices


### Listar programas
GET http://localhost:8001/programas

### Crear programa
POST http://localhost:8001/programas
Content-Type: application/json

{
    "nombre_programa": "Tecnólogo en Análisis y Desarrollo de Software"
}

###
POST http://localhost:8001/programas


### Listar profesiones
GET http://localhost:8001/profesiones

### Crear profesión
POST http://localhost:8001/profesiones
Content-Type: application/json

{
    "nombre_profesion": "Desarrollador Backend"
}


###
POST http://localhost:8001/profesiones


### Listar instructores
GET http://localhost:8001/instructores


### Crear instructores
POST http://localhost:8001/instructores
Content-Type: application/json

{
    "nombre": "Nicol ",
    "apellido": "Alarcón ",
    "email":"nicol@gmail.com",
    "telefono": "3223733929"
}
###
POST http://localhost:8001/instructores


### Listar ficha

GET  http://localhost:8001/fichas


### Crear ficha
POST http://localhost:8001/fichas
Content-Type: application/json


{
    "codigo": "2941294",
    "fecha_inicio_lectiva": "14/04/2024",
    "fecha_fin_lectiva": "23/12/2025",
    "fecha_fin_practica": "20/06/2026"
}

###
POST http://localhost:8001/fichas

